# Generated by Django 3.1.3 on 2020-11-25 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prebuilt_Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.TextField(default=' ')),
                ('desc', models.TextField(default=' ')),
                ('img', models.ImageField(default='default.jpg', upload_to='Pre_built/images')),
                ('url', models.URLField(default=' ')),
                ('price', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prebuilt_1L',
            fields=[
                ('prebuilt_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.prebuilt_base')),
            ],
            bases=('home.prebuilt_base',),
        ),
        migrations.CreateModel(
            name='Prebuilt_70k',
            fields=[
                ('prebuilt_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.prebuilt_base')),
            ],
            bases=('home.prebuilt_base',),
        ),
        migrations.CreateModel(
            name='Prebuilt_80k',
            fields=[
                ('prebuilt_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.prebuilt_base')),
            ],
            bases=('home.prebuilt_base',),
        ),
        migrations.CreateModel(
            name='Prebuilt_90k',
            fields=[
                ('prebuilt_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.prebuilt_base')),
            ],
            bases=('home.prebuilt_base',),
        ),
    ]
