# Generated by Django 3.1.2 on 2020-11-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop_Coding_Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.TextField(default=' ')),
                ('desc', models.TextField(default=' ')),
                ('img', models.ImageField(default='default.jpg', upload_to='Pre_built/images')),
                ('url', models.URLField(default=' ')),
                ('price', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_Gaming_Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.TextField(default=' ')),
                ('desc', models.TextField(default=' ')),
                ('img', models.ImageField(default='default.jpg', upload_to='Pre_built/images')),
                ('url', models.URLField(default=' ')),
                ('price', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop_Coding_30k',
            fields=[
                ('laptop_coding_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_coding_base')),
            ],
            bases=('home.laptop_coding_base',),
        ),
        migrations.CreateModel(
            name='Laptop_Coding_40k',
            fields=[
                ('laptop_coding_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_coding_base')),
            ],
            bases=('home.laptop_coding_base',),
        ),
        migrations.CreateModel(
            name='Laptop_Coding_50k',
            fields=[
                ('laptop_coding_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_coding_base')),
            ],
            bases=('home.laptop_coding_base',),
        ),
        migrations.CreateModel(
            name='Laptop_Gaming_30k',
            fields=[
                ('laptop_gaming_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_gaming_base')),
            ],
            bases=('home.laptop_gaming_base',),
        ),
        migrations.CreateModel(
            name='Laptop_Gaming_40k',
            fields=[
                ('laptop_gaming_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_gaming_base')),
            ],
            bases=('home.laptop_gaming_base',),
        ),
        migrations.CreateModel(
            name='Laptop_Gaming_50k',
            fields=[
                ('laptop_gaming_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.laptop_gaming_base')),
            ],
            bases=('home.laptop_gaming_base',),
        ),
    ]
