# Generated by Django 3.1.2 on 2020-11-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201127_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console_Base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.TextField(default=' ')),
                ('desc', models.TextField(default=' ')),
                ('img', models.ImageField(default='default.jpg', upload_to='Pre_built/images')),
                ('url', models.URLField(default=' ')),
                ('price', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Console_micro',
            fields=[
                ('console_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.console_base')),
            ],
            bases=('home.console_base',),
        ),
        migrations.CreateModel(
            name='Console_ninten',
            fields=[
                ('console_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.console_base')),
            ],
            bases=('home.console_base',),
        ),
        migrations.CreateModel(
            name='Console_sony',
            fields=[
                ('console_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.console_base')),
            ],
            bases=('home.console_base',),
        ),
    ]
