# Generated by Django 3.1.3 on 2021-01-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_console_base_console_micro_console_ninten_console_sony'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default=' ')),
                ('Post', models.TextField(default=' ')),
                ('Description', models.TextField(default=' ')),
                ('img', models.ImageField(default='default.jpg', upload_to='about/images')),
            ],
        ),
    ]
