# Generated by Django 3.1.3 on 2021-01-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210113_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='link1',
            field=models.URLField(default=' '),
        ),
        migrations.AddField(
            model_name='about',
            name='link2',
            field=models.URLField(default=' '),
        ),
    ]
